### ISSUE TITLE
bar charts flicker at the bottom

### ISSUE THREAD

**Issue by nilslindemann** [kiln/example-bar-chart#3]
Hi, thanks for flourish, this rocks!

I have created [four bar charts](https://public.flourish.studio/visualisation/1916362/) with Flourish.

Today i uploaded the most recent dataset and updated the heading texts. I did not change anything else.

Since then all four charts flicker at the bottom in Chrome. They did not do this before.

When observing this in the chrome dev tools i can see that `.flourish-embed > iframe` constantly changes its `height` property inside of the `style` attribute from `712px` to `733px` and then back.

In Firefox it does not change.

Can you confirm this behaviour?

Greetings, Nils

**Comment by daanlouter** [comment]
Hi Nils,

Thanks for reporting this. We can reproduce the problem on our side too, so we will investigate this further.

This repository is not related to the actual bar chart race template, so will close this issue here. If you have any more questions/reports, write to us at support@flourish.studio :)

Thanks again,
Daan

**Comment by nilslindemann** [comment]
Hi Daan, thanks for your answer.

Sorry for posting to the wrong repo, would you mind pointing me to the right one? Because i just detected another bug (links not working in chrome).

Edit: Ok, ignore that, i will write to that mail (i should really read messages from start to end ...)

Greetings,
Nils

**Comment by daanlouter** [comment]
Hi Nils,

The template repositories are private. So best place to report bugs are by sending them over to support@flourish.studio :)

Thanks again,
Daan
